---
title: "About"
---

My name is Phat Do.

I am a libertarian. I hope I pronounce librarian correctly. I love books since it helps me procrastinate - which means avoiding the reality. Books make me feel less guilty since reading means I am doing something meaningful. 

I love books, stories, history, philosophy, and maths. 

My ultimate goal for life is having fun by following my curiosity with scorching passion (literally).

I am obsessed with death. I already planned my death. I will have a big library made of woods and books, in the last moment of my life, I will burn the library which I have built my entire life. 

If you are curious about why my behaviour is so "mad", shortly speaking, that just some buddist thing which stuck in my head. When the feeling there I will write it down (hopefully the time will come someday). So ... look forward until then.

My passions vary a lot overtime since my brain receptors are kind of cooked (deep fried).

> I’m convinced that the only thing that kept me going was that I loved what I did. You’ve got to find what you love. And that is as true for your work as it is for your lovers. Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven’t found it yet, keep looking. Don’t settle. As with all matters of the heart, you’ll know when you find it. And, like any great relationship, it just gets better and better as the years roll on. So keep looking until you find it. Don’t settle.

I love Elon Musk (no homo but still... he's a cool guy) and Steve Jobs. I want to find more "niche" figures for being different but these 2 guys are just... too outstanding and unmatched for me.  

